### ISSUE TITLE
施老师好

### ISSUE THREAD

**Issue by HuuuNan** [cs210-566/lecture#1]
施老师请问你之前说的发烧友视频是哪个呀，我第一周没有去听课。

**Comment by ShiZhan** [comment]
能翻墙可以看YouTube，这里还有B站来源

https://space.bilibili.com/12434430#!/
LinusTechTips

推荐先看看这么几期：

80张Vega组超算 https://www.bilibili.com/video/av8000998/
加拿大超算 https://www.bilibili.com/video/av11861050
大型主机 https://www.bilibili.com/video/av13802225
AMD瑞龙 https://www.bilibili.com/video/av11331255
酷睿i9 https://www.bilibili.com/video/av11680988
4路志强E7 https://www.bilibili.com/video/av6343743
1PB硬盘 https://www.bilibili.com/video/av12303757 ， https://www.bilibili.com/video/av11651010
24固态盘 https://www.bilibili.com/video/av10397055
50万人直播 https://www.bilibili.com/video/av8000998/

**Comment by HuuuNan** [comment]
好的谢谢老师
